---
- name: Install Nrpe and Plugins
  apt: pkg={{ item.package }} 
       state=latest
       update_cache=yes
       install_recommends=no
  with_items: nrpe_agent_{{ ansible_os_family }}
  tags:
   - install-only 

- name: Copy working init file 
  copy: src=nagios-nrpe-server dest=/etc/init.d/nagios-nrpe-server mode=0755 

- name: Copy Nrpe Configuration
  template: src=nrpe.cfg.j2
            dest={{ nrpe_agent_config }}
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - restart nagios-nrpe-server
  tags:
   - config-only

